public class Constants {

    /* -------------------------------------------------------------------------------------------------------------------- */
    /*  COMMON  */
    /* -------------------------------------------------------------------------------------------------------------------- */
    public static final Integer DEFAULT_LOOKUP_LIMIT = 30;
    public static final Integer DEFAULT_LOOKUP_QUERY_LIMIT = 15;
    public static final Integer DEFAULT_QUERY_LIMIT = 10000;

}